### PR TITLE
Adding Sarah to the Advocacy Page

### PR DESCRIPTION
**Pull request by drguthals**
Adding myself to the [Cloud Advocacy page](https://developer.microsoft.com/advocates).

This is the first version, may update in the future :)

### CODE REVIEW

**Comment by drguthals** [comment]
Woah - picture is not shoing up well 😆 

One sec...

**Comment by drguthals** [comment]
I've ensure the photo I upload is only 240x360 pixels so I'm not sure why it's still showing up so large. I will address this shortly.

**Comment by drguthals** [comment]
Finally read the error message and saw that the issue was the image needed to be the same height and width :)

**Comment by drguthals** [comment]
@MaximRouiller - ready for review ✔️

**Comment by MaximRouiller** [comment]
Awesome! Thank you for being patient for 27 days @drguthals !

**Pull request merged**
