### PR TITLE
Update index.html.yml

### PR DESCRIPTION
**Pull request by brunoborges**
Add link to GitHub

### CODE REVIEW

**Comment by naveens41** [comment]
changes are already in, index files has to be generated by script, not manually.

**Comment by brunoborges** [comment]
Hey @naveens41, I don't see these changes merged anywhere.

**Comment by naveens41** [comment]
Hi Bruno,


Actually index, TOC and MAP files are autogenerated and any PR related to that will be voided.


Please let me know if you don't see your changes. Send it to me or create a new PR and I ll take care of those.


Sorry for late response, This msg went to my build notification folder.


Thanks

Naveen

________________________________

**Comment by brunoborges** [comment]
Hi @naveens41,

The website still does *not* show my change to index. This is a line I have tried to add several times and still doesn't show.

https://github.com/brunoborges/cloud-developer-advocates/blob/2b261034cf89fddb9e57949b44608e2e4abbc9b2/advocates/index.html.yml#L13-L14

What is the ideal process to submit changes like this in the future, by using Pull Requests on this GitHub repository? Sending you changes over email is not one of them.

**Comment by naveens41** [comment]
Actually index files are autogenerated and it picks the content only from the profiles.


I even don't know if anything you want to change additional to index file, they have standard templates and I dont have control over that.


Ideally you are supposed to change your profile(unless you are a part of dev team) and it will be picked up in next cycle.


Hope that helps!


Thanks

Naveen

________________________________

**Pull request closed without merging**
