### PR TITLE
Add Video, tweak bio

### PR DESCRIPTION
**Pull request by paladique**

### CODE REVIEW

**Comment by naveens41** [comment]
Hi @paladique ,
It seems that there are some conflicts with your PR. Could you resolve that and make sure that your Pr is not having any errors.
Also please add your profile photo like other profiles.

Let me know once done and passed without errors

**Comment by paladique** [comment]
@naveens41 All good now! 👍 Double checked the profile photo, it should already be up there.

**Comment by naveens41** [comment]
Hi @paladique , sorry, I didnt get your profilew photo. Could you help me finding that. or create a new CR with yml and photo together.

**Comment by paladique** [comment]
@naveens41 [it's here in master](https://github.com/MicrosoftDocs/cloud-developer-advocates/blob/master/advocates/media/profiles/jasmine-greenaway.png) I just made an update to it to add the video

**Comment by naveens41** [comment]
@paladique , All bits are tested live...Happy weekend!

**Pull request merged**
